openapi: 3.0.0

info:
  description: Groovyschool is an online learning platform for technologies in the Groovy ecosystem.
  version: 1.0.0
  title: GROOVYSCHOOL API

paths:
  /register:
    post:
      summary: Register New User
      description: Create the accout of a new student in our system
      operationId: registerUser
      requestBody:
        content:
            application/json:
              schema:
                $ref: 'schemas/User.yaml'
      responses:
        '200':
          description: ok
        '405':
          $ref: "#components/responses/405Error"






components: 
  
  responses:
    500Error:
      description: "Internal Server Error, This is the default code that is used for all server errors"
      content:
        application/json:
          schema: {}
           
    400Error:
      description: "The request wrongly formulated. For example when a required property is missing in the request body"
      content:
        application/json:
          schema: {}
           
    401Error:
      description: "The request has not been applied because it lacks valid authentication credentials for the target resource."
      content:
        application/json:
          schema: {}    
    403Error:
      description: "The request was understood but is not authorize."
      content:
        application/json:
          schema: {}
    404Error:
      description: "The resource requested was not found."
      content:
        application/json:
          schema: {}
    405Error: 
      description: "Invalid input"
      content:
        application/json:
          schema: {}
              
    
      
     